spring: 
  devtools:
    restart:
      #启动热部署
      enabled: true
      #设置修改时需要重启的目录
      additioanal-paths: src/main/java
      #设置修改不需要重启的目录
      exclude: resources/**
  datasource:
  url: jdbc:mysql://localhost:3306/test?useUnicode=true&charsetEncoding=utf-8&useSSL=true&serverTimeZone=Asia/Shanghai&nullCatalogMeansCurrent=true
  username: root
  password: 123456

server:
  port: 8888

swagger: 
  enabled: true

jwt:
  header: Access-Token
  token-start-with: Bearer
